<a href="https://colab.research.google.com/github/caniletgo/ML/blob/main/%D0%9B%D0%A01_%D0%9C%D0%9D_%D0%A7%D0%B5%D1%80%D0%BD%D0%B8%D1%88_3_10_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторна робота 1. NumPy

**Тема:** основи роботи з бібліотекою NumPy, масиви, вектори та матриці.

### Правила роботи
- Виконуйте завдання послідовно.
- Для обчислень використовуйте можливості **NumPy**.
- Не замінюйте операції NumPy звичайними Python-циклами, якщо це прямо не вказано в умові.
- Після виконання кожного завдання виводьте отриманий результат.


## 0. Підготовка середовища

### Завдання 0
Імпортуйте бібліотеку NumPy з псевдонімом `np`. Виведіть версію встановленої бібліотеки NumPy.

In [1]:
import numpy as np

print("NumPy version:", np.__version__)



NumPy version: 2.1.3


## 1. Створення масивів NumPy

### Завдання 1
Створіть одновимірний NumPy-масив із чисел:
`[2, 4, 6, 8, 10]`.

Виведіть масив та його тип за допомогою `type()`.

In [2]:
arr = np.array([2, 4, 6, 8, 10])

print("Масив:", arr)

print("Тип:", type(arr))

Масив: [ 2  4  6  8 10]
Тип: <class 'numpy.ndarray'>


### Завдання 2
Створіть:
1. масив із 10 нулів;
2. масив із 8 одиниць;
3. масив із 6 елементів, усі значення яких дорівнюють `7`.

Використайте відповідні функції NumPy.

In [3]:
zeros_arr = np.zeros(10)
ones_arr = np.ones(8)
sevens_arr = np.full(6, 7)

print(zeros_arr)
print(ones_arr)
print(sevens_arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1.]
[7 7 7 7 7 7]


### Завдання 3
Створіть масив цілих чисел від `1` до `20` включно.

Після цього створіть окремий масив парних чисел від `2` до `20`.

In [4]:
arr1 = np.arange(1, 21)
arr2 = np.arange(2, 21, 2)

print("Масив від 1 до 20:", arr1)
print("Масив парних чисел від 2 до 20:", arr2)


Масив від 1 до 20: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Масив парних чисел від 2 до 20: [ 2  4  6  8 10 12 14 16 18 20]


### Завдання 4
За допомогою `np.linspace()` створіть масив із **11 рівновіддалених чисел** від `0` до `1` включно.

In [5]:
arr = np.linspace(0, 1, 11)
print("Масив:", arr)

Масив: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


### Завдання 5
Створіть матрицю розміром `3 × 4`, заповнену числами від `1` до `12`.

Спочатку створіть одновимірний масив, а потім змініть його форму.

In [6]:
arr = np.arange(1, 13)
matrix = arr.reshape(3, 4)

print("Результат:\n", matrix)


Результат:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## 2. Основні характеристики масивів

### Завдання 6
Для матриці, створеної у попередньому завданні, визначте та виведіть:
- кількість вимірів;
- форму;
- загальну кількість елементів;
- тип даних елементів.

Використайте атрибути `ndim`, `shape`, `size`, `dtype`.

In [7]:
print("Кількість вимірів:", matrix.ndim)
print("Форма:", matrix.shape)
print("Загальна кількість елементів:", matrix.size)
print("Тип даних елементів:", matrix.dtype)

Кількість вимірів: 2
Форма: (3, 4)
Загальна кількість елементів: 12
Тип даних елементів: int64


### Завдання 7
Створіть масив:
`[1.2, 3.5, 5.7, 7.9]`.

Перетворіть його елементи на цілі числа за допомогою `astype()` та виведіть новий масив.

In [9]:
arr = np.array ([1.2, 3.5, 5.7, 7.9])
int_arr = arr.astype(int)

print(arr)
print(int_arr)

[1.2 3.5 5.7 7.9]
[1 3 5 7]


## 3. Індексація та зрізи

### Завдання 8
Створіть масив:
`[10, 20, 30, 40, 50, 60, 70, 80]`.

Виведіть:
1. перший елемент;
2. останній елемент;
3. елементи з індексами від `2` до `5` включно;
4. кожен другий елемент.

In [10]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])

print("Перший елемент:", arr[0])
print("останній елемент:", arr[-1])
print("Елементи з індексами 2-5:", arr[2:6])
print("Кожен другий елемент:", arr[::2])

Перший елемент: 10
останній елемент: 80
Елементи з індексами 2-5: [30 40 50 60]
Кожен другий елемент: [10 30 50 70]


### Завдання 9
Створіть матрицю:

```text
[[ 1,  2,  3,  4],
 [ 5,  6,  7,  8],
 [ 9, 10, 11, 12]]
```

Виведіть:
1. елемент `7`;
2. другий рядок;
3. третій стовпець;
4. підматрицю з останніх двох рядків і перших двох стовпців.

In [11]:
matrix = np.array([
 [ 1,  2,  3,  4],
 [ 5,  6,  7,  8],
 [ 9, 10, 11, 12]
])

print("Елемент 7:", matrix[1,2])
print("Другий рядок:", matrix[1])
print("Третій стовпець:", matrix[:, 2])
print("Підматриця:")
print(matrix[1,2])

Елемент 7: 7
Другий рядок: [5 6 7 8]
Третій стовпець: [ 3  7 11]
Підматриця:
7


### Завдання 10
Створіть масив чисел від `1` до `15`.

Замініть усі елементи з індексами від `5` до `9` включно на число `0`.

In [12]:
arr = np.arange(1, 16)
arr[5:10] = 0

print(arr)

[ 1  2  3  4  5  0  0  0  0  0 11 12 13 14 15]


## 4. Арифметичні операції та агрегатні функції

### Завдання 11
Створіть два масиви:

```python
a = [1, 2, 3, 4, 5]
b = [10, 20, 30, 40, 50]
```

Виконайте поелементно:
- додавання;
- віднімання;
- множення;
- ділення.

In [13]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print("Додавання:", a + b)
print("Віднімання:", a - b)
print("Множення:", a * b)
print("Ділення:", a / b)

Додавання: [11 22 33 44 55]
Віднімання: [ -9 -18 -27 -36 -45]
Множення: [ 10  40  90 160 250]
Ділення: [0.1 0.1 0.1 0.1 0.1]


### Завдання 12
Для масиву:

`[4, 8, 15, 16, 23, 42]`

обчисліть:
- суму;
- середнє значення;
- мінімум;
- максимум;
- медіану;
- стандартне відхилення.

In [14]:
arr = np.array([4, 8, 15, 16, 23, 42])

print("Сума:", np.sum(arr))
print("Середнє:", np.mean(arr))
print("Мінімум:", np.min(arr))
print("Максимум:", np.max(arr))
print("Медіана:", np.median(arr))
print("Стандартне відхилення:", np.std(arr))

Сума: 108
Середнє: 18.0
Мінімум: 4
Максимум: 42
Медіана: 15.5
Стандартне відхилення: 12.315302134607444


### Завдання 13
Створіть матрицю:

```text
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
```

Обчисліть:
1. суму всіх елементів;
2. суму по кожному стовпцю;
3. суму по кожному рядку;
4. середнє значення по кожному стовпцю.

In [15]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Сума всіх елементів:", np.sum(matrix))
print("Сума по стовпцях:", np.sum(matrix, axis=0))
print("Сума по рядках:", np.sum(matrix, axis=1))
print("Середнє по стовпцях:", np.mean(matrix, axis=0))

Сума всіх елементів: 45
Сума по стовпцях: [12 15 18]
Сума по рядках: [ 6 15 24]
Середнє по стовпцях: [4. 5. 6.]


### Завдання 14
Для масиву чисел від `1` до `10` обчисліть:
- квадрат кожного елемента;
- квадратний корінь кожного елемента;
- натуральний логарифм кожного елемента.

Використайте функції NumPy.

In [16]:
arr = np.arange(1, 11)

print("Квадрати:", np.square(arr))
print("Квадратні корені:", np.sqrt(arr))
print("Натуральні логарифми:", np.log(arr))

Квадрати: [  1   4   9  16  25  36  49  64  81 100]
Квадратні корені: [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
Натуральні логарифми: [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]


## 5. Логічні операції та фільтрація

### Завдання 15
Створіть масив:

`[3, 7, 12, 18, 21, 25, 30, 34]`

За допомогою булевої маски виведіть:
1. усі числа, більші за `15`;
2. усі парні числа;
3. числа в діапазоні від `10` до `30` включно.

In [17]:
arr = np.array([3, 7, 12, 18, 21, 25, 30, 34])

print("Більші за 15:", arr[arr > 15])
print("Парні:", arr[arr % 2 == 0])
print("Від 10 до 30 включно:", arr[(arr >= 10) & (arr <= 30)])

Більші за 15: [18 21 25 30 34]
Парні: [12 18 30 34]
Від 10 до 30 включно: [12 18 21 25 30]


### Завдання 16
Для масиву:

`[-5, 3, -2, 8, -1, 10, 0]`

замініть усі від’ємні значення на `0`.

Не використовуйте цикл `for`.

In [18]:
arr = np.array([-5, 3, -2, 8, -1, 10, 0])
arr[arr < 0] = 0

print(arr)

[ 0  3  0  8  0 10  0]


### Завдання 17
Створіть масив випадкових цілих чисел від `0` до `100` розміром `20`.

Порахуйте:
- скільки елементів більші за `50`;
- скільки елементів менші або дорівнюють `50`.

Для відтворюваності встановіть `np.random.seed(42)`.

In [19]:
np.random.seed(42)

arr = np.random.randint(0, 101, size=20)

print(arr)
print("Кількість > 50:", np.sum(arr > 50))
print("Кількість <= 50:", np.sum(arr <= 50))

[51 92 14 71 60 20 82 86 74 74 87 99 23  2 21 52  1 87 29 37]
Кількість > 50: 12
Кількість <= 50: 8


## 6. Зміна форми та об'єднання масивів

### Завдання 18
Створіть масив чисел від `1` до `24`.

Перетворіть його:
1. у матрицю `4 × 6`;
2. у матрицю `6 × 4`;
3. у тривимірний масив форми `2 × 3 × 4`.

Після кожного перетворення виведіть `shape`.

In [20]:
arr = np.arange(1, 25)

matrix_4x6 = arr.reshape(4, 6)
matrix_6x4 = arr.reshape(6, 4)
array_2x3x4 = arr.reshape(2, 3, 4)

print(matrix_4x6)
print("shape:", matrix_4x6.shape)

print(matrix_6x4)
print("shape:", matrix_6x4.shape)

print(array_2x3x4)
print("shape:", array_2x3x4.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
shape: (4, 6)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
shape: (6, 4)
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
shape: (2, 3, 4)


### Завдання 19
Створіть дві матриці:

```text
A = [[1, 2],
     [3, 4]]

B = [[5, 6],
     [7, 8]]
```

Об’єднайте їх:
1. вертикально;
2. горизонтально.

Використайте функції NumPy.

In [21]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

vertical = np.vstack((A, B))
horizontal = np.hstack((A, B))

print("Вертикальне об'єднання:")
print(vertical)

print("Горизонтальне об'єднання:")
print(horizontal)

Вертикальне об'єднання:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Горизонтальне об'єднання:
[[1 2 5 6]
 [3 4 7 8]]


### Завдання 20
Створіть матрицю `3 × 4` із числами від `1` до `12`.

Перетворіть її назад в одновимірний масив двома способами:
- за допомогою `flatten()`;
- за допомогою `ravel()`.

Порівняйте результати.

In [22]:
matrix = np.arange(1, 13).reshape(3, 4)

flat_1 = matrix.flatten()
flat_2 = matrix.ravel()

print("flatten():", flat_1)
print("ravel():", flat_2)
print("Результати однакові:", np.array_equal(flat_1, flat_2))

flatten(): [ 1  2  3  4  5  6  7  8  9 10 11 12]
ravel(): [ 1  2  3  4  5  6  7  8  9 10 11 12]
Результати однакові: True


## 7. Дії з векторами

### Завдання 21
Дано два вектори:

```text
a = [2, 4, 6]
b = [1, 3, 5]
```

Знайдіть:
- суму векторів;
- різницю векторів;
- результат множення кожного вектора на число `3`.

In [23]:
a = np.array([2, 4, 6])
b = np.array([1, 3, 5])

print("Сума:", a + b)
print("Різниця:", a - b)
print("a * 3:", a * 3)
print("b * 3:", b * 3)

Сума: [ 3  7 11]
Різниця: [1 1 1]
a * 3: [ 6 12 18]
b * 3: [ 3  9 15]


### Завдання 22
Для векторів:

```text
a = [1, 2, 3]
b = [4, 5, 6]
```

Обчисліть їх **скалярний добуток** двома способами:
1. за допомогою `np.dot()`;
2. за допомогою оператора `@`.

In [24]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("np.dot():", np.dot(a, b))
print("Оператор @:", a @ b)

np.dot(): 32
Оператор @: 32


### Завдання 23
Для вектора:

```text
v = [3, 4]
```

обчисліть його евклідову норму.

Потім нормалізуйте вектор, тобто отримайте вектор одиничної довжини.

In [25]:
v = np.array([3, 4])

norm = np.linalg.norm(v)
normalized_v = v / norm

print("Норма:", norm)
print("Нормалізований вектор:", normalized_v)

Норма: 5.0
Нормалізований вектор: [0.6 0.8]


### Завдання 24
Дано вектори:

```text
a = [1, 0, 0]
b = [0, 1, 0]
```

Знайдіть їх векторний добуток за допомогою `np.cross()`.

In [26]:
a = np.array([1, 0, 0])
b = np.array([0, 1, 0])

cross_product = np.cross(a, b)

print(cross_product)

[0 0 1]


### Завдання 25
Дано два вектори:

```text
a = [1, 2]
b = [2, 1]
```

Обчисліть косинус кута між ними за формулою через скалярний добуток і норми векторів.

Додатково знайдіть сам кут у градусах.

In [27]:
a = np.array([1, 2])
b = np.array([2, 1])

cos_angle = np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))
angle_degrees = np.degrees(np.arccos(cos_angle))

print("Косинус кута:", cos_angle)
print("Кут у градусах:", angle_degrees)


Косинус кута: 0.7999999999999998
Кут у градусах: 36.86989764584404


## 8. Дії з матрицями

### Завдання 26
Дано матрицю:

```text
A = [[1, 2, 3],
     [4, 5, 6]]
```

Знайдіть транспоновану матрицю двома способами:
1. за допомогою `.T`;
2. за допомогою `np.transpose()`.

In [28]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Через .T:")
print(A.T)

print("Через np.transpose():")
print(np.transpose(A))

Через .T:
[[1 4]
 [2 5]
 [3 6]]
Через np.transpose():
[[1 4]
 [2 5]
 [3 6]]


### Завдання 27
Дано матриці:

```text
A = [[1, 2],
     [3, 4]]

B = [[2, 0],
     [1, 2]]
```

Обчисліть:
1. поелементний добуток `A * B`;
2. матричний добуток `A @ B`.

Поясніть у коментарі до коду, чим відрізняються ці операції.

In [29]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [2, 0],
    [1, 2]
])

elementwise = A * B
matrix_product = A @ B

print("Поелементний добуток:")
print(elementwise)

print("Матричний добуток:")
print(matrix_product)

# A * B множить відповідні елементи матриць.
# A @ B виконує матричне множення: рядки A множаться на стовпці B.

Поелементний добуток:
[[2 0]
 [3 8]]
Матричний добуток:
[[ 4  4]
 [10  8]]


### Завдання 28
Для матриці:

```text
A = [[4, 7],
     [2, 6]]
```

обчисліть:
- визначник;
- обернену матрицю.

Перевірте результат, помноживши початкову матрицю на обернену.

In [30]:
A = np.array([
    [4, 7],
    [2, 6]
])

det_A = np.linalg.det(A)
inv_A = np.linalg.inv(A)
check = A @ inv_A

print("Визначник:", det_A)
print("Обернена матриця:")
print(inv_A)
print("Перевірка:")
print(check)

Визначник: 10.000000000000002
Обернена матриця:
[[ 0.6 -0.7]
 [-0.2  0.4]]
Перевірка:
[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


### Завдання 29
Розв’яжіть систему лінійних рівнянь за допомогою NumPy:

```text
2x +  y = 5
 x + 3y = 6
```

Сформуйте матрицю коефіцієнтів `A` і вектор правих частин `b`.

Використайте `np.linalg.solve()`.

In [31]:
A = np.array([
    [2, 1],
    [1, 3]
])

b = np.array([5, 6])

solution = np.linalg.solve(A, b)

print("Розв'язок:", solution)

Розв'язок: [1.8 1.4]


### Завдання 30
Створіть одиничну матрицю розміром `4 × 4`.

Перевірте властивість одиничної матриці: помножте на неї довільну матрицю `4 × 4` та порівняйте результат з початковою матрицею.

In [32]:
I = np.eye(4)

A = np.arange(1, 17).reshape(4, 4)
result = A @ I

print("Одинична матриця:")
print(I)

print("Початкова матриця:")
print(A)

print("Результат множення:")
print(result)

print("Матриці однакові:", np.allclose(A, result))


Одинична матриця:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Початкова матриця:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Результат множення:
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
Матриці однакові: True


## 9. Broadcasting (операція трансляції)

### Завдання 31
Створіть матрицю:

```text
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
```

Додайте число `10` до кожного її елемента.

In [33]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

result = A + 10

print(result)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


### Завдання 32
До матриці:

```text
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
```

додайте вектор:

```text
v = [10, 20, 30]
```

Проаналізуйте, як NumPy застосував broadcasting.

In [34]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

v = np.array([10, 20, 30])

result = A + v

print(result)

# Вектор v додається до кожного рядка матриці A.

[[11 22 33]
 [14 25 36]
 [17 28 39]]


### Завдання 33
Нормалізуйте **кожен стовпець** матриці:

```text
A = [[10, 20, 30],
     [20, 30, 40],
     [30, 40, 50]]
```

за формулою:

\[
z = \frac{x - \mu}{\sigma}
\]

де `μ` — середнє значення стовпця, `σ` — стандартне відхилення стовпця.

Не використовуйте цикл `for`.

In [35]:
A = np.array([
    [10, 20, 30],
    [20, 30, 40],
    [30, 40, 50]
])

mean = np.mean(A, axis=0)
std = np.std(A, axis=0)

normalized = (A - mean) / std

print(normalized)

[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


## 10. Випадкові дані

### Завдання 34
Встановіть `np.random.seed(42)` та створіть:
1. 10 випадкових цілих чисел від `1` до `100`;
2. матрицю `3 × 3` випадкових чисел від `0` до `1`;
3. 1000 значень із нормального розподілу.

Для третього масиву обчисліть середнє та стандартне відхилення.

In [36]:
np.random.seed(42)

random_ints = np.random.randint(1, 101, size=10)
random_matrix = np.random.random((3, 3))
normal_values = np.random.normal(size=1000)

print("Випадкові цілі числа:", random_ints)
print("Матриця 3x3:")
print(random_matrix)
print("Середнє нормального розподілу:", np.mean(normal_values))
print("Стандартне відхилення:", np.std(normal_values))

Випадкові цілі числа: [52 93 15 72 61 21 83 87 75 75]
Матриця 3x3:
[[0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264]
 [0.21233911 0.18182497 0.18340451]]
Середнє нормального розподілу: 0.02216865975826456
Стандартне відхилення: 0.9792284455184356


### Завдання 35
Змоделюйте оцінки 30 студентів — випадкові цілі числа від `0` до `100`.

Визначте:
- середню оцінку;
- медіану;
- найвищу та найнижчу оцінки;
- кількість студентів, які отримали не менше `60`;
- відсоток студентів, які отримали не менше `90`.

In [37]:
grades = np.random.randint(0, 101, size=30)

print("Оцінки:", grades)
print("Середня оцінка:", np.mean(grades))
print("Медіана:", np.median(grades))
print("Найвища оцінка:", np.max(grades))
print("Найнижча оцінка:", np.min(grades))
print("Кількість студентів з оцінкою >= 60:", np.sum(grades >= 60))
print("Відсоток студентів з оцінкою >= 90:", np.mean(grades >= 90) * 100)

Оцінки: [25  2 40 59 13 74 81 11 86 11 12 24 44 18 54 99 44  7 92 52 54 31 50 43
 81 69 17 82 21 36]
Середня оцінка: 44.4
Медіана: 43.5
Найвища оцінка: 99
Найнижча оцінка: 2
Кількість студентів з оцінкою >= 60: 8
Відсоток студентів з оцінкою >= 90: 6.666666666666667


## 11. Підсумкові завдання

### Завдання 36
Дано результати продажів трьох товарів за чотири місяці:

```text
sales = [[120, 150, 170, 160],
         [80,  90,  100, 110],
         [200, 180, 210, 230]]
```

Рядки — товари, стовпці — місяці.

Визначте:
1. загальний обсяг продажів кожного товару;
2. загальний обсяг продажів у кожному місяці;
3. товар із найбільшими сумарними продажами;
4. місяць із найбільшим загальним обсягом продажів;
5. середній обсяг продажів кожного товару.

In [39]:
sales = [[120, 150, 170, 160], [80, 90, 100, 110], [200, 180, 210, 230]]

arr = np.array(sales)

prod_totals = arr.sum(axis=1)
print("1. Загальний обсяг продажів кожного товару:", prod_totals)

month_totals = arr.sum(axis=0)
print("2. Загальний обсяг продажів у кожному місяці:", month_totals)

print(f"3. Товар із найбільшими продажами: Товар {prod_totals.argmax() + 1}")
print(
    f"4. Місяць із найбільшим обсягом продажів: Місяць {month_totals.argmax() + 1}"
)
print("5. Середній обсяг продажів кожного товару:", arr.mean(axis=1))

1. Загальний обсяг продажів кожного товару: [600 380 820]
2. Загальний обсяг продажів у кожному місяці: [400 420 480 500]
3. Товар із найбільшими продажами: Товар 3
4. Місяць із найбільшим обсягом продажів: Місяць 4
5. Середній обсяг продажів кожного товару: [150.  95. 205.]


### Завдання 37
Створіть квадратну матрицю `5 × 5` із випадкових цілих чисел від `1` до `20`.

Виконайте:
1. знайдіть суму головної діагоналі;
2. знайдіть суму побічної діагоналі;
3. знайдіть максимальний елемент кожного рядка;
4. знайдіть мінімальний елемент кожного стовпця;
5. замініть усі елементи, менші за середнє значення всієї матриці, на `0`.

In [40]:
matrix = np.random.randint(1, 21, size=(5, 5))
print("Початкова матриця:\n", matrix)

print("1. Сума головної діагоналі:", np.trace(matrix))
print("2. Сума побічної діагоналі:", np.fliplr(matrix).diagonal().sum())
print("3. Максимальний елемент кожного рядка:", matrix.max(axis=1))
print("4. Мінімальний елемент кожного стовпця:", matrix.min(axis=0))

matrix[matrix < matrix.mean()] = 0
print("5. Матриця після заміни елементів на 0:\n", matrix)

Початкова матриця:
 [[ 9  3 10 19  3]
 [15  1  7 12 17]
 [20  5  4 12 20]
 [18 17 19  9  4]
 [ 2  4  2 15  2]]
1. Сума головної діагоналі: 25
2. Сума побічної діагоналі: 38
3. Максимальний елемент кожного рядка: [19 17 20 19 15]
4. Мінімальний елемент кожного стовпця: [2 1 2 9 2]
5. Матриця після заміни елементів на 0:
 [[ 0  0 10 19  0]
 [15  0  0 12 17]
 [20  0  0 12 20]
 [18 17 19  0  0]
 [ 0  0  0 15  0]]


### Завдання 38
Дано матрицю ознак трьох об’єктів:

```text
X = [[2, 4, 6],
     [1, 3, 5],
     [5, 7, 9]]
```

Обчисліть **евклідову відстань** між:
- першим і другим рядком;
- першим і третім рядком;
- другим і третім рядком.

Використайте операції NumPy та `np.linalg.norm()`.

In [41]:
X = np.array([[2, 4, 6], [1, 3, 5], [5, 7, 9]])

d1_2 = np.linalg.norm(X[0] - X[1])
d1_3 = np.linalg.norm(X[0] - X[2])
d2_3 = np.linalg.norm(X[1] - X[2])

print("Відстань між першим і другим рядком:", d1_2)
print("Відстань між першим і третім рядком:", d1_3)
print("Відстань між другим і третім рядком:", d2_3)

Відстань між першим і другим рядком: 1.7320508075688772
Відстань між першим і третім рядком: 5.196152422706632
Відстань між другим і третім рядком: 6.928203230275509


### Завдання 39
Створіть матрицю `4 × 4` із довільних цілих чисел.

Для кожного рядка знайдіть його норму та створіть нову матрицю, у якій кожен рядок нормалізований до одиничної довжини.

Спробуйте виконати завдання без циклів.

In [42]:
matrix = np.random.randint(1, 10, size=(4, 4))
print("Початкова матриця:\n", matrix)

norms = np.linalg.norm(matrix, axis=1, keepdims=True)
print("\nНорми рядків:\n", norms.flatten())

normalized_matrix = matrix / norms
print("\nНормалізована матриця:\n", normalized_matrix)

Початкова матриця:
 [[4 6 7 3]
 [3 6 3 2]
 [8 5 1 3]
 [8 4 7 2]]

Норми рядків:
 [10.48808848  7.61577311  9.94987437 11.53256259]

Нормалізована матриця:
 [[0.38138504 0.57207755 0.66742381 0.28603878]
 [0.3939193  0.7878386  0.3939193  0.26261287]
 [0.80403025 0.50251891 0.10050378 0.30151134]
 [0.69368798 0.34684399 0.60697698 0.17342199]]


### Завдання 40
Створіть матрицю коефіцієнтів і вектор правих частин для системи:

```text
 x + 2y +  z =  9
2x +  y -  z =  8
3x -  y + 2z =  3
```

1. Розв’яжіть систему за допомогою `np.linalg.solve()`.
2. Перевірте знайдений розв’язок матричним множенням `A @ x`.
3. Порівняйте результат із вектором `b`.

In [43]:
A = np.array([[1, 2, 1], [2, 1, -1], [3, -1, 2]])
b = np.array([9, 8, 3])

x = np.linalg.solve(A, b)
print("1. Розв'язок системи:", x)

check = A @ x
print("2. Результат A @ x:", check)

print("3. Чи збігається результат із b:", np.allclose(check, b))

1. Розв'язок системи: [ 2.22222222  3.44444444 -0.11111111]
2. Результат A @ x: [9. 8. 3.]
3. Чи збігається результат із b: True


---

## Самоперевірка

Після виконання роботи студент повинен уміти:
- створювати та перетворювати NumPy-масиви;
- використовувати індексацію та зрізи;
- виконувати векторизовані арифметичні операції;
- застосовувати агрегатні функції;
- використовувати булеві маски;
- змінювати форму та об'єднувати масиви;
- виконувати основні дії з векторами;
- виконувати основні операції з матрицями;
- застосовувати broadcasting;
- використовувати функції `numpy.linalg` для задач лінійної алгебри.
